{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sehatq-toko.fullname" . }}
  labels:
    {{- include "sehatq-toko.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sehatq-toko.selectorLabels" . | nindent 4 }}
{{- end }}